{{- include "ffc-helm-library.container-config-map" (list . "ffc-pay-file-publisher.config-map") -}}
{{- define "ffc-pay-file-publisher.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  MESSAGE_QUEUE_HOST: {{ quote .Values.container.messageQueueHost }}
  {{- if and (.Values.environmentCode) (not .Values.pr) }}
  SEND_TOPIC_ADDRESS: {{ .Values.container.sendTopicAddress }}-{{ .Values.environmentCode }}
  EVENTS_TOPIC_ADDRESS: {{ .Values.container.eventsTopicAddress }}-{{ .Values.environmentCode }}
  {{ else }}
  SEND_TOPIC_ADDRESS: {{ quote .Values.container.sendTopicAddress }}
  EVENTS_TOPIC_ADDRESS: {{ quote .Values.container.eventsTopicAddress }}
  {{- end }}
  SEND_SUBSCRIPTION_ADDRESS: {{ quote .Values.container.sendSubscriptionAddress }}  
  AZURE_STORAGE_ACCOUNT_NAME: {{ quote .Values.container.azureStorageAccountName }}
  AZURE_STORAGE_CONNECTION_STRING: {{ quote .Values.container.azureStorageConnectionString }}
  AZURE_STORAGE_USE_CONNECTION_STRING: {{ quote .Values.container.azureStorageUseConnectionString }}
  AZURE_STORAGE_CREATE_CONTAINERS: {{ quote .Values.container.azureStorageCreateContainers }}
  DAX_STORAGE_CONNECTION_STRING: {{ quote .Values.container.daxStorageConnectionString }}
  DAX_STORAGE_SHARE_NAME: {{ quote .Values.container.daxStorageShareName }}
  AP_FOLDER: {{ quote .Values.container.apFolder }}
  AR_FOLDER: {{ quote .Values.container.arFolder }}
  DPS_FOLDER: {{ quote .Values.container.dpsFolder }}
  USE_EVENTS: {{ quote .Values.container.useEvents }}
  FILE_PUBLISH_ENABLED: {{ quote .Values.container.filePublishEnabled }}
{{- end -}}
