services:
  ffc-pay-file-publisher:
    build:
      context: .
      target: production
    image: ffc-pay-file-publisher
    container_name: ffc-pay-file-publisher
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-pay-file-publisher-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
