# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-pay-file-publisher:
    build:
      target: development
    image: ffc-pay-file-publisher-development
    container_name: ffc-pay-file-publisher-development
    ports:
      - "9261:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
    environment:
      AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://ffc-pay-dax-azurite:10000/devstoreaccount1;
    depends_on:
      - ffc-pay-dax-azurite

  ffc-pay-dax-azurite:
    volumes:
      - azurite_data:/data
    ports:
      - "10061:10000"

volumes:
  azurite_data:
