services:
  ffc-pay-file-publisher:
    build:
      context: .
      target: production
    image: ffc-pay-file-publisher
    container_name: ffc-pay-file-publisher
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-pay-file-publisher-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      PAYMENTSUBMIT_TOPIC_ADDRESS: ${PAYMENTSUBMIT_TOPIC_ADDRESS:-ffc-pay-submit}${MESSAGE_QUEUE_SUFFIX}
      PAYMENTSUBMIT_SUBSCRIPTION_ADDRESS: ${PAYMENTSUBMIT_SUBSCRIPTION_ADDRESS:-ffc-pay-submission}${MESSAGE_QUEUE_SUFFIX}
      AZURE_STORAGE_ACCOUNT_NAME: ${AZURE_STORAGE_ACCOUNT_NAME:-devstoreaccount1}
      AZURE_STORAGE_USE_CONNECTION_STRING: "true"
      DAX_STORAGE_CONNECTION_STRING: ${DAX_STORAGE_CONNECTION_STRING}

  ffc-pay-file-publisher-azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.17.1
    command: "azurite-blob --loose --blobHost 0.0.0.0"
